### ISSUE TITLE
New QueryThread on start_batch may be inefficient

### ISSUE THREAD

**Issue by egorps** [spilgames/pyvertica#19]
Currently, the VerticaBatch will start up a new thread every time _start_batch is called. Depending on how the batch is used, this may not be desirable. For example, we would like to keep a batch open for an indefinite amount of time, and execute a commit every N seconds. So, this means every N seconds, a new thread is going to get started up and the old one will be shut down. I think it would be better to just reuse the old thread where possible.

I'm planning to fix this issue, let me know what you think!

**Comment by lomignet** [comment]
Indeed, reusing the thread could only be a good thing, and that would be a great addition to the time based commit.

**Comment by egorps** [comment]
work in progress...
https://github.com/hpcs-som/pyvertica/tree/taskthread
